export * from "@/pages/home";
export * from "@/pages/profile";
export * from "@/pages/project/ProjectList";
export * from "@/pages/chat/community";
export * from "@/pages/chat/chat";
export * from "@/pages/contact/contact";
export * from "@/pages/Login";
export * from "@/pages/Register";
export * from "@/pages/prueba";
